In [1]:
import pandas as pd
import pickle

In [2]:
df=pd.read_csv('corona.csv.txt')
df.head()

title  \
0  Due to the recent outbreak for the Coronavirus...   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                                                text  \
0  You just need to add water, and the drugs and ...   
1  Hydroxychloroquine has been shown to have a 10...   
2  Fact: Hydroxychloroquine has been shown to hav...   
3  The Corona virus is a man made virus created i...   
4  Doesn’t @BillGates finance research at the Wuh...   

                      source label  
0  coronavirusmedicalkit.com  Fake  
1               RudyGiuliani  Fake  
2                CharlieKirk  Fake  
3    JoanneWrightForCongress  Fake  
4    JoanneWrightForCongress  Fake

In [3]:
df.head(15)

title  \
0   Due to the recent outbreak for the Coronavirus...   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5   CORONA UNMASKED: Chinese Intelligence Officer ...   
6                                                 NaN   
7                                                 NaN   
8                                                 NaN   
9   Basic protective measures against the new coro...   
10                                                NaN   
11                                                NaN   
12                                                NaN   
13                                                NaN   
14  Exposing yourself to the sun or to temperature...   

                                                 text  \
0   You just need to add water, and the drugs and ...   
1   Hydroxychloroquine has been shown to have a 10...   
2   Fact: Hydroxychloroquine has been shown to hav...   
3   The Corona virus is a man made virus created i...   
4   Doesn’t @BillGates finance research at the Wuh...   
5                                                 NaN   
6   Urgent: Health Bulletin to the Public. Ministr...   
7   Pls tell ur families, relatives and friendsMOH...   
8   SERIOUS EXCELLENT ADVICE by Japanese doctors t...   
9   Stay aware of the latest information on the CO...   
10  The new Coronavirus may not show signs of infe...   
11  A vaccine meant for cattle can be used to figh...   
12  Using a hair dryer to breathe in hot air can c...   
13  Corona virus before it reaches the lungs it re...   
14  You can catch COVID-19, no matter how sunny or...   

                                               source label  
0                           coronavirusmedicalkit.com  Fake  
1                                        RudyGiuliani  Fake  
2                                         CharlieKirk  Fake  
3                             JoanneWrightForCongress  Fake  
4                             JoanneWrightForCongress  Fake  
5                                                 NaN   NaN  
6                                  Ministry of Health  Fake  
7                                              NWLLAB  Fake  
8            Japanese doctors treating COVID-19 cases  Fake  
9   https://www.who.int/emergencies/diseases/novel...  TRUE  
10                                     Taiwan Experts  Fake  
11                                           facebook  Fake  
12                                            Youtube  Fake  
13                                            twitter  Fake  
14  https://www.who.int/emergencies/diseases/novel...  TRUE

In [4]:
df.drop(['title'],axis=1,inplace=True)
df.drop(['source'],axis=1,inplace=True)

In [5]:
df.isnull().sum()

text     10
label     5
dtype: int64

In [6]:
df_New=df.dropna()

In [7]:
df.shape

(1164, 2)

In [8]:
df_New.isnull().sum()

text     0
label    0
dtype: int64

In [9]:
df_New.shape

(1151, 2)

In [10]:
df_New.head(10)

text label
0   You just need to add water, and the drugs and ...  Fake
1   Hydroxychloroquine has been shown to have a 10...  Fake
2   Fact: Hydroxychloroquine has been shown to hav...  Fake
3   The Corona virus is a man made virus created i...  Fake
4   Doesn’t @BillGates finance research at the Wuh...  Fake
6   Urgent: Health Bulletin to the Public. Ministr...  Fake
7   Pls tell ur families, relatives and friendsMOH...  Fake
8   SERIOUS EXCELLENT ADVICE by Japanese doctors t...  Fake
9   Stay aware of the latest information on the CO...  TRUE
10  The new Coronavirus may not show signs of infe...  Fake

In [11]:
df_New.label.unique()

array(['Fake', 'TRUE', 'fake'], dtype=object)

In [12]:
df_New['label'].value_counts()

TRUE    581
Fake    344
fake    226
Name: label, dtype: int64

In [13]:
df_New['label']=df_New['label'].replace('fake','Fake')

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [14]:
df_New['label'].value_counts()

TRUE    581
Fake    570
Name: label, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [16]:
df_New["label"]=encoder.fit_transform(df_New['label'])

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [17]:
df_New.head(10)

text  label
0   You just need to add water, and the drugs and ...      0
1   Hydroxychloroquine has been shown to have a 10...      0
2   Fact: Hydroxychloroquine has been shown to hav...      0
3   The Corona virus is a man made virus created i...      0
4   Doesn’t @BillGates finance research at the Wuh...      0
6   Urgent: Health Bulletin to the Public. Ministr...      0
7   Pls tell ur families, relatives and friendsMOH...      0
8   SERIOUS EXCELLENT ADVICE by Japanese doctors t...      0
9   Stay aware of the latest information on the CO...      1
10  The new Coronavirus may not show signs of infe...      0

In [18]:
df_New.label.unique()

array([0, 1])

In [19]:
df_New.reset_index(inplace=True)

In [20]:
import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to C:\Users\gaurav
[nltk_data]     sahani\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
corpus = []
ps = PorterStemmer()

In [22]:
df_New['text'][5]

'Urgent: Health Bulletin to the Public. Ministry of health’s emergency notification to the public that the Coronavirus outbreak this time is very very serious & fatal. There’s no cure once you are infected. Its spreading from China to various countries. Prevention method is to keep your throat moist, do not let your throat dry up. Thus do not hold your thirst because once your membrane in your throat is dried, the virus will invade into your body within 10 mins. Drink 50-80cc warm water, 30-50cc for kids, according to age. Everytime u feel your throat is dry, do not wait, keep water in hand. Do not drink plenty at one time as it doesn’t help, instead continue to keep throat moist. Till end of March 2020, do not go to crowded places, wear mask as needed especially in train or public transportation. Avoid fried or spicy food and load up vitamin C. The symptoms/ description are. 1.repeated high fever. 2.prolonged coughing after fever.\n3.Children are prone. 4.Adults usually feel uneasy, h

In [23]:
for i in range(0, len(df_New)):
    
    text = re.sub('[^a-zA-Z]', ' ', df_New['text'][i])
    text = text.lower()
    words = text.split()
    words = [word for word in words if word not in set(stopwords.words('english'))]
    words = [ps.stem(word) for word in words]
    text = ' '.join(words)
    corpus.append(text)

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=2500)
X = tf.fit_transform(corpus).toarray()

In [25]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.03627492, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02163677, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [26]:
y = pd.get_dummies(df_New['label'])
y = y.iloc[:, 1].values

In [27]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=uint8)

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [44]:
from sklearn.naive_bayes import MultinomialNB
MultiNB= MultinomialNB()
MultiNB.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [45]:
y_pred=spam_detect_model.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1], dtype=uint8)

In [46]:
from sklearn.metrics import confusion_matrix
confusion_m = confusion_matrix(y_test,y_pred)
confusion_m

array([[115,  11],
       [  9,  96]], dtype=int64)

In [47]:
filename = 'CovidSpam-model.pkl'
pickle.dump(MultiNB, open(filename, 'wb'))