In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import pickle

In [2]:
df=pd.read_csv('COVID-19.csv')

In [3]:
df.head()

Sno  age  gender  bodytemperature  DryCough  sourthroat  weakness  \
0    1   20       1             98.6         0           0         0   
1    2   19       1             99.0         1           0         0   
2    3   55       0            102.0         1           1         1   
3    4   40       0            100.0         0           0         0   
4    5   33       1             99.2         0           1         0   

   breathingproblem  drowsiness  pain in chest  ...  diabetes  heart disease  \
0                 0           0              0  ...         0              0   
1                 0           0              0  ...         0              0   
2                 1           1              1  ...         0              0   
3                 0           1              1  ...         1              0   
4                 1           0              0  ...         0              0   

   lung disease  stroke or reduced immunity  symptoms progressed  \
0             0                           0                    0   
1             0                           0                    0   
2             0                           0                    0   
3             0                           0                    1   
4             1                           1                    1   

   high blood pressue  kidney disease  change in appetide  \
0                   0               0                   0   
1                   0               0                   0   
2                   0               0                   1   
3                   1               0                   1   
4                   0               0                   0   

   Loss of sense of smell  Result  
0                       0       0  
1                       0       0  
2                       0       1  
3                       0       2  
4                       1       2  

[5 rows x 21 columns]

In [4]:
df.shape

(127, 21)

In [5]:
df.isnull().sum()

Sno                           0
age                           0
gender                        0
bodytemperature               0
DryCough                      0
sourthroat                    0
weakness                      0
breathingproblem              0
drowsiness                    0
pain in chest                 0
travelhistory                 0
diabetes                      0
heart disease                 0
lung disease                  0
stroke or reduced immunity    0
symptoms progressed           0
high blood pressue            0
kidney disease                0
change in appetide            0
Loss of sense of smell        0
Result                        0
dtype: int64

In [6]:
df_New=df[['age','gender','bodytemperature','DryCough','sourthroat','weakness','breathingproblem','diabetes','drowsiness','travelhistory','Result']]

In [7]:
df_New.head()

age  gender  bodytemperature  DryCough  sourthroat  weakness  \
0   20       1             98.6         0           0         0   
1   19       1             99.0         1           0         0   
2   55       0            102.0         1           1         1   
3   40       0            100.0         0           0         0   
4   33       1             99.2         0           1         0   

   breathingproblem  diabetes  drowsiness  travelhistory  Result  
0                 0         0           0              0       0  
1                 0         0           0              0       0  
2                 1         0           1              0       1  
3                 0         1           1              1       2  
4                 1         0           0              1       2

In [8]:
df['Result'].unique()

array([0, 1, 2], dtype=int64)

In [9]:
df['Result'].value_counts()

1    69
0    33
2    25
Name: Result, dtype: int64

In [10]:
X=df_New.drop(['Result'],axis=1)
y=df_New[['Result']]

In [11]:
X.head()

age  gender  bodytemperature  DryCough  sourthroat  weakness  \
0   20       1             98.6         0           0         0   
1   19       1             99.0         1           0         0   
2   55       0            102.0         1           1         1   
3   40       0            100.0         0           0         0   
4   33       1             99.2         0           1         0   

   breathingproblem  diabetes  drowsiness  travelhistory  
0                 0         0           0              0  
1                 0         0           0              0  
2                 1         0           1              0  
3                 0         1           1              1  
4                 1         0           0              1

In [12]:
y.head()

Result
0       0
1       0
2       1
3       2
4       2

In [160]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.151, random_state=1)

In [161]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(max_depth=2, n_estimators=220, min_samples_leaf=1)

In [162]:
rf.fit(X_train, y_train)

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=220,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [163]:
pred1=rf.predict(X_test)
pred1

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
      dtype=int64)

In [164]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test, pred1))
print(confusion_matrix(y_test, pred1))

0.75
[[ 2  3  0]
 [ 0 13  0]
 [ 0  2  0]]


In [165]:
filename = 'CovidSymtoms.pkl'
pickle.dump(rf, open(filename, 'wb'))